apiVersion: v1
kind: Service
metadata:
  name: {{ include "preview.name" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: app
    {{- include "preview.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
